name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v1

    # ! dependents on other library
    - name: Update Submodules
      run: git submodule update --remote

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Generate otera library
      run: python3 library_generator.py

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: oj-verify all
